# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/points',
                'doc_host': 'https://xiaochuany.github.io',
                'git_url': 'https://github.com/xiaochuany/points',
                'lib_path': 'points'},
  'syms': {'points.core': {'points.core.Po': ('core.html#po', 'points/core.py')}}}
