# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['Po']

# %% ../nbs/00_core.ipynb 3
import numpy as np

# %% ../nbs/00_core.ipynb 4
def Po(lam:float=1.0)->int: 
    return np.random.default_rng().poisson(lam, size=(1,))[0]
